function(add_sdl_library name root)
    add_library(PkgConfig::${name} SHARED IMPORTED)
    if(CMAKE_SIZEOF_VOID_P STREQUAL 8)
        set(lib_prefix "x64")
    else()
        set(lib_prefix "x86")
    endif()
    set(library_directory "${root}/lib/${lib_prefix}")
    set_property(TARGET PkgConfig::${name} PROPERTY IMPORTED_IMPLIB "${library_directory}/${name}.lib")
    set_property(TARGET PkgConfig::${name} PROPERTY IMPORTED_LOCATION "${library_directory}/${name}.dll")
    set_property(TARGET PkgConfig::${name} PROPERTY INTERFACE_INCLUDE_DIRECTORIES "${root}/include")
    foreach(binary ${ARGN})
        install(FILES "${library_directory}/${binary}" DESTINATION bin)
    endforeach()
endfunction()
